on:
  push:
    branches:
      - main
name: release-please
permissions: write-all
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          include-v-in-tag: false
          release-type: simple
          package-name: release-please-action
